-- -- ~/.config/nvim/lua/config/options.lua
-- -- Add these lines to your existing options file
--
-- -- Ensure transparency settings
-- vim.opt.termguicolors = true
-- vim.opt.winblend = 0
-- vim.opt.pumblend = 0
-- vim.opt.background = "dark" -- For rose-pine-moon variant
--
-- -- For terminal apps that support true transparency
-- vim.api.nvim_create_autocmd("ColorScheme", {
--   pattern = "*",
--   callback = function()
--     -- Remove all background colors
--     vim.api.nvim_set_hl(0, "Normal", { bg = "NONE", ctermbg = "NONE" })
--     vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE", ctermbg = "NONE" })
--     vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE", ctermbg = "NONE" })
--     vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE", ctermbg = "NONE" })
--     vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "NONE", ctermbg = "NONE" })
--     vim.api.nvim_set_hl(0, "LineNr", { bg = "NONE", ctermbg = "NONE" })
--   end,
-- })
